{
    model: "GCN_PSP",
    optimizer: "SGD",

    max_epochs: 12,
    batch_size: 3,

    lr: 0.00002,
    weight_decay: 0.0005,
    momentum: 0.98,

    K: 17,

    scale_factor: 0.55,
    default_img_size: !!python/tuple [1052, 1914],

    lr_decay: True,
    scheduler: "poly",
    lr_decay_freq: 1,
    lr_decay_power: 0.9,

    eval_freq: 5000,
    eval_samples: 25,

    resume: False,
    resume_epoch: 0,

    paths: {
        project_path: "/cis/home/fparker/VisDa",
        data_base_path: "/cis/home/fparker/data",
        data_train_path: "/cis/home/fparker/data/train/",
        cityscapes_path: "/cis/home/fparker/data/cityscapes/",
        cityscapes_val_path: "/cis/home/fparker/data/cityscapes_eval/",
        pretrained_models_path: "/cis/home/fparker/data/pretrained/"
    }

}
