{
	max_epochs: 20,
	batch_size: 2,

	lr: 2e-5,
	weight_decay: 0.0005,
	momentum: 0.98,

	K: 15,

	scale_factor: 0.8,
	default_img_size: [1052, 1914],
	img_size: [841, 1531],

	lr_decay_freq: 1,
	lr_decay_rate: 2,

	base_path: "/home/flixpar/VisDa",
	base_data_path: "/media/data/train/",
}