{
    model: "GCN",
    optimizer: "SGD",

    max_epochs: 12,
    batch_size: 6,

    lr: 0.00002,
    weight_decay: 0.0005,
    momentum: 0.98,

    K: 17,

    scale_factor: 0.45,
    default_img_size: !!python/tuple [1052, 1914],

    lr_decay: True,
    lr_decay_freq: 1,
    lr_decay_power: 0.9,

    eval_freq: 5000,
    eval_samples: 25,

    resume: True,
    resume_epoch: 2,

    paths: {
        project_path: "/home/flixpar/VisDa",
        data_base_path: "/media/data/",
        data_train_path: "/media/data/train/",
        cityscapes_path: "/media/data/cityscapes/",
        cityscapes_val_path: "/media/data/cityscapes_eval/",
        pretrained_models_path: "/media/data/pretrained/"
    }

}
