{
    model: "GCN",
    optimizer: "Adam",

    max_epochs: 20,
    batch_size: 8,

    lr: !!float 2e-5,
    weight_decay: 0.0005,
    momentum: 0.98,

    K: 13,

    scale_factor: 0.4,
    default_img_size: !!python/tuple [1052, 1914],

    lr_decay: False,
    lr_decay_freq: 1,
    lr_decay_power: 0.9,

    eval_freq: 1000,

    resume: False,
    resume_epoch: 1,
}
